### ISSUE TITLE
使用Line取代原先的登入方式

### ISSUE THREAD

**Issue by TainanPublicWitnessing** [Tainan-Public-Witnessing/tainan-public-witnessing#32]
考慮弟兄姊妹大多數人使用Line以及現在帳號密碼的安全性。希望在將來把登入方式改為使用Line來登入

- [ ] 新成員建檔時，給予一組random code，然後新成員加入時根據這組code進行Line綁定
- [x] Line身份綁定

**Comment by xellosiris** [comment]
- [ ] 不再需要受浸日期的欄位
- [ ] Tag標籤的移除

**Comment by xellosiris** [comment]
- [ ] 確定大家都可以成功登入後，刪除UserKeys collection，並且確保程式碼運作不受影響
- [ ] 前端Line notify switch 要使用環境變數
